In [5]:
## Numpy == Numerical Python 
import numpy as np

In [6]:
# array 생성
test_array = np.array(["1","2",3,4],float) # String 과 int 타입이 들어가 있지만 float을 선언함으로써 float으로 통일

print(test_array)
type(test_array)

[1. 2. 3. 4.]


numpy.ndarray

In [7]:
# dtype

print(test_array.dtype)

float64


In [13]:
# shape
test_array = np.array(["1","2",3,4],float)

print(test_array.shape)

(4,)


In [25]:
# reshape
test_matrix = [[1,2,3,4],[1,2,4,8]]
print(f'origin:{np.array(test_matrix).shape}')

print(np.array(test_matrix).reshape(2,2,2))
print('\n')
print(np.array(test_matrix).reshape(8,))
print('\n')
print(np.array(test_matrix).reshape(2,4))

origin:(2, 4)
[[[1 2]
  [3 4]]

 [[1 2]
  [4 8]]]


[1 2 3 4 1 2 4 8]


[[1 2 3 4]
 [1 2 4 8]]


In [30]:
# indexing
a = np.array([[1,2,3],[4.5,5,6]], int)
print(a)
print(a[0,0])
print(a[0][0])

a[0,0] = 12
print(a)

a[0][1] = 15
print(a)

[[1 2 3]
 [4 5 6]]
1
1
[[12  2  3]
 [ 4  5  6]]
[[12 15  3]
 [ 4  5  6]]


In [34]:
# Slicing

a = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
print(a)

print(a[:,2:]) # 전체 row의 2열 이상
print(a[:,0:3]) # 전체 row의 0~3 columns

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 3  4  5]
 [ 8  9 10]]
[[1 2 3]
 [6 7 8]]


In [36]:
# arange

np.arange(30) # 0~29 까지 배열 추출 

np.arange(30).reshape(-1,5) # reshape 사용

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [42]:
# ones, zeros and empty

print(np.zeros(shape=(10,), dtype=np.int8))
print(np.ones(shape=(10,), dtype=np.int8))
print(np.empty(shape=(10,), dtype=np.int8))

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1]


In [47]:
# something_list
test_matrix = np.arange(30).reshape(5,6)
print(test_matrix)
np.ones_like(test_matrix)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [51]:
# identity : 단위 행렬(i 행렬)을 생성함 

print(np.identity(n=3, dtype=np.int8))
print('\n')
print(np.identity(5))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [60]:
# eye : 대각선이 1인 행렬, k값의 시작 index의 변경이 가능
print(np.eye(N=3, M=5, dtype=np.int8))
print('\n')
print(np.eye(3))
print('\n')
print(np.eye(3,5,k=2))# k : start index

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [64]:
# diag : 대각 행렬의 값을 추출함 
matrix = np.arange(9).reshape(3,3)
print(matrix)
print(np.diag(matrix))
print(np.diag(matrix, k=1)) # k : start index

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[1 5]


In [66]:
# random sampling : 데이터 분포에 따른 sampling으로 array를 생성 
print(np.random.uniform(0,1,10).reshape(2,5)) # uniform : 균등분포 
print(np.random.normal(0,1,10).reshape(2,5)) # normal : 정규분포 

[[0.68544567 0.21626028 0.98826108 0.25044664 0.65487989]
 [0.32321514 0.21706292 0.54038442 0.53911161 0.34826248]]
[[-0.22283061  0.02322825 -0.70398275 -0.55852037 -0.01682508]
 [ 1.20484381  0.34678623 -1.6381438  -0.85101087  1.53891355]]


In [77]:
# axis : 모든 operation function을 실행할 때, 기준이 되는 dimension 축 

test_array = np.arange(1,13).reshape(3,4)
print(test_array)
print(test_array.sum(axis=0))
print(test_array.sum(axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[15 18 21 24]
[10 26 42]


In [79]:
# concatenate : Numpy array를 합치는 함수 
a = np.array([1,2,3])
b = np.array([2,3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [2 3 4]]
[1 2 3 2 3 4]


In [86]:
# operations b/t arrays : Numpy는 array간의 기본적인 사칙 연산을 지원함
test_a = np.array([[1,2,3],[4,5,6]], float)
print(test_a + test_a)
print(test_a - test_a)
print(test_a * test_a)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [89]:
# Dot product 
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
print(test_a)
print(test_b)
test_a.dot(test_b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


array([[ 58,  64],
       [139, 154]])

In [93]:
# transpose
test_a = np.arange(1,7).reshape(2,3)
print(f'origin:{test_a}')
print(f'transpose:{test_a.transpose()}')

origin:[[1 2 3]
 [4 5 6]]
transpose:[[1 4]
 [2 5]
 [3 6]]


In [96]:
# broadcasting : Shape이 다른 배열 간 연산을 지원하는 기능 

test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 2

print(test_matrix + scalar)
print(test_matrix - scalar)
print(test_matrix * scalar)
print(test_matrix / scalar)
print(test_matrix // scalar) # 몫
print(test_matrix ** scalar) # 제곱 

[[3. 4. 5.]
 [6. 7. 8.]]
[[-1.  0.  1.]
 [ 2.  3.  4.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[0. 1. 1.]
 [2. 2. 3.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [108]:
## Comparisons
# All&Any
a = np.arange(10)
print(a)
print(a<0)
print(a>=0)

print(np.any(a<0))
print(np.all(a>=0))

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True  True]
False
True


In [113]:
# np.where
a = np.arange(10)
print(np.where(a>0,3,2)) # true = 3, False = 2 를 반환 
print(np.where(a>3)) # index 값 반환 

a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

[2 3 3 3 3 3 3 3 3 3]
(array([4, 5, 6, 7, 8, 9], dtype=int64),)


array([False,  True, False])

In [117]:
# argmax&argmin : 가장 큰 값 , 가장 작은 값의 index를 반환 
a = np.array([1,2,4,5,8,78,23,2])
print(np.argmax(a), np.argmin(a))

a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
print(np.argmax(a, axis=1), np.argmin(a, axis=0))

5 0
[3 1 1] [0 0 2 2]


In [122]:
# Boolean index
test_array = np.array([1,4,0,2,3,8,9,7],float)
test_array > 3

print(test_array[test_array > 3]) # 조건이 True 인 index의 element만 추출 

condition = test_array < 3 # 조건 
test_array[condition] # 3보다 작은 element 만 

[4. 8. 9. 7.]


array([1., 0., 2.])

In [126]:
# fancy index : numpy 는 array를 index value로 사용해서 값을 추출하는 방법 

a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int) # 반드시 integer로 선언 
print(a[b]) # bracket index, b 배열의 값을 index로 하여 a의 값들을 추출함 

a.take(b) # take 함수 : bracket index와 같은 효과 
print(a.take(b))

# 명확하게 사용하는 take 함수를 추천 

[2. 2. 4. 8. 6. 4.]
[2. 2. 4. 8. 6. 4.]
